version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: ./docker-entrypoint.sh gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./:/app:rw
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://banking:banking@db:5432/banking
      - DEBUG=1
      - RUN_MIGRATIONS=1
      - COLLECT_STATIC=0
    depends_on:
      - db
volumes:
  db_data:
