# Generated by Django 5.2.7 on 2025-10-17 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_amlcheck_backupjob_loan_loanpayment_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('end_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('start_user_agent', models.CharField(blank=True, max_length=512)),
                ('end_user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('impersonator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_target', to=settings.AUTH_USER_MODEL)),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_terminated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['impersonator'], name='banking_imp_imperso_e37b78_idx'), models.Index(fields=['target'], name='banking_imp_target__e1f18d_idx')],
            },
        ),
    ]
