name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: banking
          POSTGRES_PASSWORD: banking
          POSTGRES_DB: banking
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U banking" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pip-audit pytest pytest-django

      - name: Run linters
        run: |
          pre-commit run --all-files || true
          flake8 backend || true

      - name: Run bandit (SAST)
        run: |
          bandit -r backend -q

      - name: Dependency audit (pip-audit)
        run: |
          pip-audit -q --format json > pip_audit.json || true
          cat pip_audit.json

      - name: Run tests
        env:
          DATABASE_URL: postgres://banking:banking@127.0.0.1:5432/banking
        run: |
          python backend/manage.py migrate --noinput || true
          pytest -q || true
