name: Image Scan

on:
  push:
    branches: [ main ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t registry.example.com/yourproject/backend:${{ github.sha }} backend/

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: registry.example.com/yourproject/backend:${{ github.sha }}
